// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FlutterError {
  return FlutterError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum ThermalLevel: Int {
  case nominal = 0
  case fair = 1
  case serious = 2
  case critical = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct TrackingConfig {
  var useFrontCamera: Bool

  static func fromList(_ list: [Any?]) -> TrackingConfig? {
    let useFrontCamera = list[0] as! Bool

    return TrackingConfig(
      useFrontCamera: useFrontCamera
    )
  }
  func toList() -> [Any?] {
    return [
      useFrontCamera
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BallDetection {
  var x: Double
  var y: Double
  var width: Double
  var height: Double
  var confidence: Double
  var isKalmanPrediction: Bool

  static func fromList(_ list: [Any?]) -> BallDetection? {
    let x = list[0] as! Double
    let y = list[1] as! Double
    let width = list[2] as! Double
    let height = list[3] as! Double
    let confidence = list[4] as! Double
    let isKalmanPrediction = list[5] as! Bool

    return BallDetection(
      x: x,
      y: y,
      width: width,
      height: height,
      confidence: confidence,
      isKalmanPrediction: isKalmanPrediction
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
      width,
      height,
      confidence,
      isKalmanPrediction,
    ]
  }
}

private class BallTrackerApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return TrackingConfig.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BallTrackerApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? TrackingConfig {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BallTrackerApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BallTrackerApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BallTrackerApiCodecWriter(data: data)
  }
}

class BallTrackerApiCodec: FlutterStandardMessageCodec {
  static let shared = BallTrackerApiCodec(readerWriter: BallTrackerApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BallTrackerApi {
  func startTracking(config: TrackingConfig, completion: @escaping (Result<Int64, Error>) -> Void)
  func stopTracking() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BallTrackerApiSetup {
  /// The codec used by BallTrackerApi.
  static var codec: FlutterStandardMessageCodec { BallTrackerApiCodec.shared }
  /// Sets up an instance of `BallTrackerApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BallTrackerApi?) {
    let startTrackingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.swoosh.BallTrackerApi.startTracking", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startTrackingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! TrackingConfig
        api.startTracking(config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startTrackingChannel.setMessageHandler(nil)
    }
    let stopTrackingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.swoosh.BallTrackerApi.stopTracking", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopTrackingChannel.setMessageHandler { _, reply in
        do {
          try api.stopTracking()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopTrackingChannel.setMessageHandler(nil)
    }
  }
}
private class BallDetectionApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return BallDetection.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BallDetectionApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BallDetection {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BallDetectionApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BallDetectionApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BallDetectionApiCodecWriter(data: data)
  }
}

class BallDetectionApiCodec: FlutterStandardMessageCodec {
  static let shared = BallDetectionApiCodec(readerWriter: BallDetectionApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol BallDetectionApiProtocol {
  func onDetection(detection detectionArg: BallDetection, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onThermalWarning(level levelArg: ThermalLevel, completion: @escaping (Result<Void, FlutterError>) -> Void)
}
class BallDetectionApi: BallDetectionApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger) {
    self.binaryMessenger = binaryMessenger
  }
  var codec: FlutterStandardMessageCodec {
    return BallDetectionApiCodec.shared
  }
  func onDetection(detection detectionArg: BallDetection, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.swoosh.BallDetectionApi.onDetection"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([detectionArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onThermalWarning(level levelArg: ThermalLevel, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.swoosh.BallDetectionApi.onThermalWarning"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([levelArg.rawValue] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
