// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDINMHh2LB0WOAvR3Ts9IFwP0Mg4w8daFU',
    appId: '1:887379670059:web:d6f8303005b37d2c45e66e',
    messagingSenderId: '887379670059',
    projectId: 'swoosh-27d33',
    authDomain: 'swoosh-27d33.firebaseapp.com',
    storageBucket: 'swoosh-27d33.firebasestorage.app',
    measurementId: 'G-S1JP811VS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPJBnQcRMvjluNDSDVOfmQKsJ8VXIbPi8',
    appId: '1:887379670059:android:45511982dad0ae3045e66e',
    messagingSenderId: '887379670059',
    projectId: 'swoosh-27d33',
    storageBucket: 'swoosh-27d33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIkSnHtx7rFoIlP7N0RI1bvUIWQZvJDNw',
    appId: '1:887379670059:ios:1bdf9d11cd0e99ba45e66e',
    messagingSenderId: '887379670059',
    projectId: 'swoosh-27d33',
    storageBucket: 'swoosh-27d33.firebasestorage.app',
    iosClientId: '887379670059-lanmqndui9hglp3ut5ivamccskliqv76.apps.googleusercontent.com',
    iosBundleId: 'com.example.swoosh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIkSnHtx7rFoIlP7N0RI1bvUIWQZvJDNw',
    appId: '1:887379670059:ios:1bdf9d11cd0e99ba45e66e',
    messagingSenderId: '887379670059',
    projectId: 'swoosh-27d33',
    storageBucket: 'swoosh-27d33.firebasestorage.app',
    iosClientId: '887379670059-lanmqndui9hglp3ut5ivamccskliqv76.apps.googleusercontent.com',
    iosBundleId: 'com.example.swoosh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDINMHh2LB0WOAvR3Ts9IFwP0Mg4w8daFU',
    appId: '1:887379670059:web:81d7e35ff03dec2e45e66e',
    messagingSenderId: '887379670059',
    projectId: 'swoosh-27d33',
    authDomain: 'swoosh-27d33.firebaseapp.com',
    storageBucket: 'swoosh-27d33.firebasestorage.app',
    measurementId: 'G-3HZ7SHN4WJ',
  );
}
